### ISSUE TITLE
Can't find tablet-mode.json

### ISSUE THREAD

**Issue by alexgallotta** [conqp/tablet-switch#1]
The ReadMe is asking to set up `/etc/tablet-mode.conf`, but the python scripts looks for a json file`/etc/tablet-mode.json`
```
/usr/bin/sysmoded    
[WARNING] /usr/bin/sysmoded: Config file /etc/tablet-mode.json does not exist.
[INFO] /usr/bin/sysmoded: No devices configured to disable.
```
Is there a conversion somewhere I am missing?

**Comment by conqp** [comment]
Yes. There was a migration from the INI-style *conf file to the JSON file.
Unfortunately I missed to document that.
I just updated the readme file that describes the new format.
