### ISSUE TITLE
Ask informations about your work

### ISSUE THREAD

**Issue by Tuxman2** [conqp/tablet-switch#2]
Hello,

first, thanks for your work. I've got a 2-in-1 convertible laptop (can be open 180° degrees). So it has 2 accelerometers.

I have a lot of questions :

1. I guess that your work support the 2 accelerometers ?
2. Does it support stand and tent mode ?
3. Is it possible to use scripts or line command to enable/disable on-screen keyboard, enable/disable auto rotation screen, disable options in gnome3 with your work ?
4. Have you got instructions how to install your work and for activate or deactivated touchpad and keyboard in laptop and tablet mode ?

Thanks for your reply.

**Comment by conqp** [comment]
You seem to have a completely wrong idea of what this project is about.
This project is a workaround for convertibles, where the accelerometers are not yet supported by the Linux kernel.
So to answer your questions:

1) No.
2) This is out of the scope of this project.
3) That depends on your system / DE.
4) Read the README.md.
