### ISSUE TITLE
No platform-i8042-serio-1-event-mouse in /dev/input/by-path/

### ISSUE THREAD

**Issue by Tuxman2** [conqp/tablet-switch#4]
Hello,

I tried your script and it works but only for the keyboard. My touchpad is not off. 
I don't have platform-i8042-serio-1-event-mouse in the /dev/input/by-path/ directory. Only /dev/input/by-path/platform-i8042-serio-0-event-kbd. 

So, how can I disabled my touchpad with the help of your script ?

Thanks.

**Comment by conqp** [comment]
Please excuse my late reply. You'll need to find the device path to your touch pad.
In case there is none, you're unfortunately out of luck, since tablet-mode depends on it.

**Comment by Tuxman2** [comment]
Hello,
I found the correct device path for my hardware and your script works very well now. The only think I want to know if it is possible that your script can be enabled automatically when I move the screen to 360 degrees. For now, I must use the line command or the desktop icon. Perhaps with the help of another script, or with the help of udev, or perhaps with something else ? 
Have got an idea on it ?
Thanks.
Alan.

**Comment by conqp** [comment]
As I have already mentioned [here](https://github.com/conqp/tablet-mode/issues/2#issuecomment-527120371), this is out of the scope of this project.
This project was explicitely started for manual mode switching on systems where automatic switching does not work.
