### ISSUE TITLE
How to install and use your scripts ?

### ISSUE THREAD

**Issue by Tuxman2** [conqp/tablet-switch#5]
Hi,

I don't know how I should use your scripts. Can you give me the steps to follow?

Thank you.

**Comment by conqp** [comment]
Either you use the [package from the AUR](https://aur.archlinux.org/packages/tablet-mode/) for Arch Linux or -based distributions, or you manually copy the files to the appropriate locations according to the [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard), which is similar to the paths I use within the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=tablet-mode), but the scripts located at `/usr/local/bin`.
