### ISSUE TITLE
.desktop file doesn't work

### ISSUE THREAD

**Issue by twoexem** [conqp/tablet-switch#6]
Hello!
I recently got a convertible laptop, and since it doesn't have a proper sensor for detecting a flipped display (or it does and my system doesn't detect it), I decided to install your program.

Everything worked well, setting up the file was easy and changing the mode from the console worked like a charm, so I decided to put the .desktop file onto my taskbar.

Problem is, every time I click it it doesn't change anything, and sometimes it also locks my user account for whatever reason. I don't know if it's an issue on my side or anything. but it'd be nice if you could help me. Besides that, it's a good program that I intend on using.

My system:
Medion Akoya E2291
Arch Linux
KDE Plasma
Intel GPU & GPU
If you need any more info, let me know!

**Comment by conqp** [comment]
As you can see from the desktop files's content, it does not do anything that might lock your computer.
Your issue lies somewhere else.

**Comment by twoexem** [comment]
Alright, I'll keep looking. Thanks for the quick reply, have a good evening!

Regards

**Comment by twoexem** [comment]
Small update (I swear, this will be the last one):
I've reinstalled the package again and now it works flawlessly. Thanks again for the quick response. I swear, next time I'll consider a quick reinstall before opening an issue 0.o
