### ISSUE TITLE
"No package metadata was found for tabletmode"

### ISSUE THREAD

**Issue by jloow** [conqp/tablet-switch#7]
I ran into the following error when trying to toggle tablet mode.

```
Traceback (most recent call last):
  File "/usr/bin/setsysmode", line 33, in <module>
    sys.exit(load_entry_point('tabletmode==2.2.0', 'console_scripts', 'setsysmode')())
  File "/usr/bin/setsysmode", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 957, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for tabletmode
```

After searching around on the error message, I came across this thread: https://github.com/gonzaarcr/Fildem/issues/117

I gather from that thread (and the solution) that this is an issue with tablet-mode and Python 3.10.

Running the follwing commands works as a workaround:

```
sudo ln -s /usr/lib/python3.9/site-packages/tabletmode/ /usr/lib/python3.10/site-packages/
sudo ln -s /usr/lib/python3.9/site-packages/tabletmode-2.2.0-py3.9.egg-info/ /usr/lib/python3.10/site-packages/
```

**Comment by conqp** [comment]
The linking of libraries for different Python versions is a bad idea.
If you built and installed tablet-mode for Python 3.10, you should also run it with Python 3.10.
If you want to run it under Python 3.9, you also need to build it for Python 3.9.

How did you install tablet-mode anyway?

**Comment by jloow** [comment]
I installed it through AUR, with `makepkg -si`.
I'm just a happy amateur (hence the perhaps horrible workaround) but I thought this would build tablet-mode with the latest version of Python. Is this an issue with the AUR package rather than tablet-mode?

**Comment by conqp** [comment]
The default Python version on Arch Linux is 3.10.
If you updated from Python 3.9 to Python 3.10 after you built tablet-mode, you'll need to rebuild it for Python 3.10.
And I hope, you weren't doing [partial upgrades](https://wiki.archlinux.org/title/System_maintenance#Partial_upgrades_are_unsupported).
